# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansprechpartner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansprechpartner',
            options={'verbose_name_plural': 'Ansprechpartner'},
        ),
    ]
