# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20170701_0036'),
        ('ansprechpartner', '0002_auto_20170627_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansprechpartner',
            name='contact_profiles',
            field=models.ManyToManyField(to='jobs.ContactProfile'),
        ),
    ]
