# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansprechpartner', '0004_auto_20170701_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansprechpartner',
            name='contacts',
        ),
    ]
