# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansprechpartner', '0005_remove_ansprechpartner_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansprechpartner',
            name='banner_slogan',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
