# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=64, verbose_name='Vorname')),
                ('name', models.CharField(max_length=64)),
                ('company', models.CharField(blank=True, max_length=64, verbose_name='Firma')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('subject', models.CharField(max_length=64, verbose_name='Betreff')),
                ('message', models.TextField(verbose_name='Mitteilung')),
            ],
        ),
    ]
