# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmessages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalanfrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(blank=True, max_length=64, verbose_name='Firma')),
                ('first_name', models.CharField(max_length=64, verbose_name='Vorname')),
                ('name', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64, verbose_name='Straße/Hausnummer')),
                ('city', models.CharField(max_length=64, verbose_name='PLZ/Ort')),
                ('phone', models.CharField(max_length=64, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('job', models.CharField(max_length=64, verbose_name='Bedarf/Beruf')),
                ('qualitications', models.CharField(max_length=128, verbose_name='Zusatzqualifikationen')),
                ('location', models.CharField(max_length=64, verbose_name='Einsatzort/Gebiet')),
            ],
        ),
    ]
