# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactmessages', '0003_auto_20170628_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalanfrage',
            options={'verbose_name_plural': 'Personalanfragen'},
        ),
    ]
