# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0020_auto_20170703_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logdata', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingConfirmation',
            fields=[
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Company')),
            ],
        ),
        migrations.AddField(
            model_name='confirmation',
            name='pending_confirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datenweitergabe.PendingConfirmation'),
        ),
    ]
