# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berufsfelder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bereich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berufsfelder.Bereich')),
            ],
        ),
        migrations.RemoveField(
            model_name='berufsfelder',
            name='fields',
        ),
        migrations.AddField(
            model_name='bereich',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berufsfelder.Berufsfelder'),
        ),
    ]
