# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berufsfelder', '0003_auto_20170629_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berufsfelder',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
