# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vorteile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('banner_color', models.CharField(max_length=6)),
                ('banner_slogan', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100)),
                ('pros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorteile.Pro')),
            ],
        ),
    ]
