# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorteile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vorteile.Vorteile'),
            preserve_default=False,
        ),
    ]
