# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vorteile', '0002_pro_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vorteile',
            name='pros',
        ),
    ]
