# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorteile', '0003_remove_vorteile_pros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vorteile',
            options={'verbose_name_plural': 'Vorteile'},
        ),
        migrations.AlterField(
            model_name='vorteile',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
