# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_left_entry',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='menu_left_sub_entry',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='menu_top_entry',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
