# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170629_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='banner_slogan',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(max_length=4000),
        ),
    ]
