# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170630_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=64),
        ),
    ]
