# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170630_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
