# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referenzen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='field',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='referenzen.Field'),
            preserve_default=False,
        ),
    ]
