# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referenzen', '0003_auto_20170627_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='field',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='referenzen.Page'),
            preserve_default=False,
        ),
    ]
