# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referenzen', '0005_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='banner_color',
            field=models.CharField(default='red', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='banner_slogan',
            field=models.CharField(default='x', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
