# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20170627_1033'),
        ('standorte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='locations',
        ),
        migrations.AddField(
            model_name='locations',
            name='locations',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobs.Location'),
            preserve_default=False,
        ),
    ]
