# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standorte', '0002_auto_20170627_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='locations',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
