# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bereich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kompetenzbereiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('banner_color', models.CharField(max_length=6)),
                ('banner_slogan', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100)),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompetenzbereiche.Bereich')),
            ],
        ),
        migrations.AddField(
            model_name='bereich',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompetenzbereiche.Job'),
        ),
    ]
