# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzbereiche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kompetenzbereich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('banner_color', models.CharField(max_length=6)),
                ('banner_slogan', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='kompetenzbereiche',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='bereich',
            name='jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='field',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kompetenzbereiche.Bereich'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Kompetenzbereiche',
        ),
        migrations.AddField(
            model_name='bereich',
            name='competencefield',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kompetenzbereiche.Kompetenzbereich'),
            preserve_default=False,
        ),
    ]
