# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzbereiche', '0002_auto_20170627_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bereich',
            options={'verbose_name_plural': 'Bereiche'},
        ),
        migrations.AlterModelOptions(
            name='kompetenzbereich',
            options={'verbose_name_plural': 'Kompetenzbereiche'},
        ),
    ]
