# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_changed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterField(
            model_name='location',
            name='gmaps_iframe_href',
            field=models.CharField(max_length=999),
        ),
    ]
