# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170519_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
