# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20170626_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(default='av', on_delete=django.db.models.deletion.CASCADE, to='jobs.Department'),
            preserve_default=False,
        ),
    ]
