# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20170627_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(blank=True, to='jobs.Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='states',
            field=models.ManyToManyField(blank=True, to='jobs.State'),
        ),
    ]
