# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20170701_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('priority', models.DecimalField(decimal_places=0, max_digits=2)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Contact')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Location')),
            ],
        ),
    ]
