# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 21:38
from __future__ import unicode_literals

from django.db import migrations


def transfer_profile_data(apps, schema_editor):
    Contact = apps.get_model('jobs', 'Contact')
    ContactProfile = apps.get_model('jobs', 'ContactProfile')

    for contact in Contact.objects.all():
        contact_profile = ContactProfile()

        for attr in ["status", "phone", "mail", "priority", "location"]:
            setattr(contact_profile, attr, getattr(contact, attr))

        contact_profile.contact = contact
        contact_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_contactprofile'),
    ]

    operations = [
        migrations.RunPython(transfer_profile_data),
    ]
