# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20170701_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(to='jobs.Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='states',
            field=models.ManyToManyField(to='jobs.State'),
        ),
    ]
