# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20170630_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactprofile',
            options={'ordering': ['-priority']},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
    ]
