# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20170701_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.ContactProfile'),
        ),
    ]
