# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:07
from __future__ import unicode_literals

from django.db import migrations


def attach_fk_to_job(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')

    for job in Job.objects.all():
        job.contact_profile = job.contact.contactprofile_set.first()

        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_contact_profile'),
    ]

    operations = [
        migrations.RunPython(attach_fk_to_job),
    ]
