# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_contact_profile'),
    ]

    operations = [
    ]
