# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20170701_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contact',
        ),
    ]
