# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20170701_2041'),
        ('jobs', '0014_auto_20170701_0036'),
    ]

    operations = [
    ]
