# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20170702_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
